title: ArcGIS Documentation
description: Simple documentation site for ArcGIS
baseurl: "/docs-demo"
url: "https://memestageceo.github.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/